[source]
# url to source piaware json status
url = http://127.0.0.1/status.json

[strip]
# frequency in kHz
freqency = 800
# interval to poll source data, seconds
pollinterval = 10
# led brightness, 0-255
brightness = 64
# output pin (if on pi5 / using SPI, will always use pin 10 MOSI)
pin = 10

[indicators]
# key is the json status, value is the led index
radio = 0
piaware = 1
adept = 2
gps = 3
mlat = 4